
# server port for local docker and Render
server.port=${PORT:8080}

#ORM s/w specific properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#---------------------properties file for no handler exception------------------
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

